-- AlterTable
ALTER TABLE "Bot" 
ADD COLUMN IF NOT EXISTS "tweetingEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "tweetInterval" INTEGER NOT NULL DEFAULT 180,
ADD COLUMN IF NOT EXISTS "lastTweetAt" TIMESTAMP(3); 